name: Upload HTML to S3
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::141076505187:role/service.devrel-examples
          audience: sts.amazonaws.com  # Matches the aud condition in the trust policy
          aws-region: us-west-2
      
      - name: Create dummy HTML file
        run: echo "<html><body><h1>Hello, S3!</h1></body></html>" > dummy.html
      
      - name: Upload HTML to S3
        run: aws s3 cp dummy.html s3://databricks-web-files/devrel/dummy.html
        
